# Establecer la imagen base
FROM node:latest

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalar el paquete Vue CLI globalmente
RUN npm install -g @vue/cli

# Copiar el script para crear el proyecto Vue
COPY create_vue_project.sh /create_vue_project.sh

# Dar permisos de ejecución al script
RUN chmod +x /create_vue_project.sh

# Ejecutar el script para crear el proyecto Vue
RUN /create_vue_project.sh

# Copiar los archivos del proyecto Vue al contenedor
COPY . /app

# Instalar las dependencias del proyecto
RUN npm install

# Exponer el puerto en el que se ejecutará la aplicación Vue.js
EXPOSE 3000

# Comando para iniciar la aplicación Vue.js
CMD ["npm", "run", "serve"]
