version: '3.8'

services:
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=infometrika_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - app-network

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravelfans/laravel:latest
    container_name: infometrika-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - '8080:80'
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: infometrika_db
      DB_USERNAME: root
      DB_PASSWORD: 123456
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node:latest
    container_name: infometrika-vue-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
