-- Creación de la base de datos Libreria
CREATE DATABASE Libreria;
USE Libreria;

-- Tabla para gestionar personas (autores y usuarios)
CREATE TABLE PERSON (
    PERSON_ID INT,
    FIRST_NAME VARCHAR(25),
    SECOND_NAME VARCHAR(25),
    FIRST_LAST_NAME VARCHAR(25),
    SECOND_LAST_NAME VARCHAR(25),
    DATE_OF_BIRTH DATE,
    STATUS TINYINT(1),
    CREATED_AT DATE,
    UPDATED_AT DATE,
    PRIMARY KEY (PERSON_ID)
);

-- Tabla para gestionar roles
CREATE TABLE ROLE (
    ROLE_ID INT NOT NULL,
    ROLE_NAME VARCHAR(45),
    CREATED_AT DATE NULL,
    UPDATED_AT DATE NULL,
    PRIMARY KEY (ROLE_ID)
);

-- Tabla para gestionar usuarios
CREATE TABLE USER (
    USER_ID INT,
    USERNAME VARCHAR(25),
    PASSWORD CHAR(25),
    EMAIL VARCHAR(45),
    STATUS TINYINT(1),
    PERSON_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATED_AT DATE NULL,
    UPDATED_AT DATE NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT fk_USER_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID),
    CONSTRAINT fk_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID)
);

-- Tabla para gestionar libros
CREATE TABLE BOOK (
    BOOK_ID INT,
    CODE VARCHAR(45),
    TITLE TEXT,
    DESCRIPTION TEXT,
    NUM_COPIES INT,
    UNIT_PRICE INT,
    ISBN INT,
    YEAR_PUBLISHED DATETIME NULL,
    EDITION_NUM INT,
    NUM_PAGES VARCHAR(45),
    AUTHOR_ID INT NOT NULL,
    LANGUAGE_ID INT NOT NULL,
    PUBLISHER_ID INT NOT NULL,
    CREATED_AT DATE NULL,
    UPDATED_AT DATE NULL,
    PRIMARY KEY (BOOK_ID),
    CONSTRAINT fk_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID),
    CONSTRAINT fk_BOOK_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (LANGUAGE_ID),
    CONSTRAINT fk_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (PUBLISHER_ID)
);

-- Tabla para gestionar préstamos de libros
CREATE TABLE LOAN (
    LOAN_ID INT,
    BOOK_ID INT,
    USER_ID INT,
    LOAN_DATE DATE,
    RETURN_DATE DATE,
    STATUS TINYINT(1),
    PRIMARY KEY (LOAN_ID),
    CONSTRAINT fk_LOAN_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID),
    CONSTRAINT fk_LOAN_USER FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

-- Tabla para gestionar autores
CREATE TABLE AUTHOR (
    AUTHOR_ID INT,
    PERSON_ID INT NOT NULL,
    BIOGRAPHY TEXT,
    COUNTRY_OF_BIRTH CHAR(2),      -- País de nacimiento del autor (Códigos ISO 3166-1 alpha-2)
    DATE_OF_DEATH DATE,            -- Fecha de fallecimiento (opcional)
    PRIMARY KEY (AUTHOR_ID),
    CONSTRAINT fk_AUTHOR_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID),
    CONSTRAINT chk_AUTHOR_COUNTRY CHECK (COUNTRY_OF_BIRTH IN ('CO', 'EC', 'VE'))  -- Restricción para país de nacimiento
);

-- Tabla para gestionar idiomas
CREATE TABLE LANGUAGE (
    LANGUAGE_ID INT,
    LANGUAGE_NAME VARCHAR(25),
    PRIMARY KEY (LANGUAGE_ID)
);

-- Tabla para gestionar Publisher
CREATE TABLE PUBLISHER (
    PUBLISHER_ID INT,
    COMPANY TEXT,
    WEBSITE TEXT NULL,
    PRIMARY KEY (PUBLISHER_ID)
);

